# Generated by Django 6.0.4 on 2026-04-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_business_lead_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
