# Generated by Django 6.0.4 on 2026-04-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_first_response_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='whatsapp_sent',
            field=models.BooleanField(default=False),
        ),
    ]
